name: Calculator CI

on:
  pull_request:
    branches: [master]

jobs:
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: checkout code from repository
        uses: actions/checkout@v5
      - name: install dependencies
        run: npm ci
      - name: check code formatting
        run: npm run prettier:check --if-present
      - name: lint the code
        run: npm run lint:check --if-present
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: code-quality
    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x]
    steps:
      - name: checkout code from repository
        uses: actions/checkout@v5
      - name: setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - name: install dependencies
        run: npm ci
      - name: test module
        run: npm test
  coverage:
    name: Create Coverage Report
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: checkout code from repository
        uses: actions/checkout@v5
      - name: install dependencies
        run: npm ci
      - name: test module and generate coverage
        run: npm run test:coverage --if-present
      - name: Coverage report
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2
